sudo: required
dist: trusty
group: edge
language: python
services:
  - docker

# Disable depth (for ./autogen.sh --system to pass)
git:
  depth: 9999999

env:
  matrix:
    - DOCKER_IMAGE=ovirtorg/vdsm-test-centos
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-25
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-rawhide

before_install:
  - docker --version
  - docker pull $DOCKER_IMAGE

script:
  - docker run --env TRAVIS_CI=1 --privileged --rm -it -v `pwd`:/vdsm:Z $DOCKER_IMAGE bash -c "cd /vdsm && ./autogen.sh --system && make && make --jobs=2 check"
